config/routes.rb
Rails.application.routes.draw do
  resources :rounds
  resources :games
  root 'games#index'
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id         :uuid             not null, primary key
#  owner      :string
#  player1    :string           not null
#  player2    :string           not null
#  player3    :string           not null
#  player4    :string           not null
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Game < ApplicationRecord
  has_many :rounds # cascade delete done in database

  validates :name, presence: true
  validates :player1, presence: true
  validates :player2, presence: true
  validates :player3, presence: true
  validates :player4, presence: true

  def score1
    rounds.sum(:score1)
  end

  def score2
    rounds.sum(:score2)
  end

  def score3
    rounds.sum(:score3)
  end

  def score4
    rounds.sum(:score4)
  end

  def score_sign1
    score1 >= 0 ? 'pos' : 'neg'
  end

  def score_sign2
    score2 >= 0 ? 'pos' : 'neg'
  end

  def score_sign3
    score3 >= 0 ? 'pos' : 'neg'
  end

  def score_sign4
    score4 >= 0 ? 'pos' : 'neg'
  end

  def winner1
    score1 == max_score ? 'winner' : 'looser'
  end

  def winner2
    score2 == max_score ? 'winner' : 'looser'
  end

  def winner3
    score3 == max_score ? 'winner' : 'looser'
  end

  def winner4
    score4 == max_score ? 'winner' : 'looser'
  end

  def scores
    [score1, score2, score3, score4]
  end

  def max_score
    scores.compact.max
  end

  #####################

  def self.new_from_ip(ip)
    Game.new(player1: Faker::Name.first_name,
             player2: Faker::Name.first_name,
             player3: Faker::Name.first_name,
             player4: Faker::Name.first_name,
             name: name_from_ip(ip))
  end

  def self.name_from_ip(ip)
    response = HTTParty.get("http://api.ipstack.com/#{ip}?access_key=2d186e4c34beb6881385a1a65698f023")
    location = "#{response["city"]}/#{response["country_name"]}" if response["city"]
    "#{location}@#{Time.zone.now.to_date.to_s(:short)}"
  end
end

app/models/round.rb
# == Schema Information
#
# Table name: rounds
#
#  id         :bigint(8)        not null, primary key
#  game_id    :uuid
#  score1     :integer
#  score2     :integer
#  score3     :integer
#  score4     :integer
#  roundtype  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Round < ApplicationRecord
  belongs_to :game

  validate :correct_score

  before_save :derive

  def correct_score
    case scores.compact.count
    when 1
      errors.add :base, "single score should be divisible by 3" if scores.compact.first % 3 != 0
    when 2
      errors.add :base, "two scores should be equal" if scores.compact.first != scores.compact.second
    when 4
      errors.add :base, "scores should sum up to 0" if scores.compact.sum != 0
      errors.add :base, "there cannot be more than 2 different score valeus" if scores.uniq.count > 2
    end
  end

  def derive
    if valid?
      case scores.compact.count
      when 1
        score = -max_score/3
        self.score1 = score if score1.blank?
        self.score2 = score if score2.blank?
        self.score3 = score if score3.blank?
        self.score4 = score if score4.blank?
      when 2
        score = -max_score
        self.score1 = score if score1.blank?
        self.score2 = score if score2.blank?
        self.score3 = score if score3.blank?
        self.score4 = score if score4.blank?
      when 3
        score = -max_score*3
        self.score1 = score if score1.blank?
        self.score2 = score if score2.blank?
        self.score3 = score if score3.blank?
        self.score4 = score if score4.blank?
      end
    end
    self
  end

  def score_sign1
    score1 >= 0 ? 'pos' : 'neg'
  end

  def score_sign2
    score2 >= 0 ? 'pos' : 'neg'
  end

  def score_sign3
    score3 >= 0 ? 'pos' : 'neg'
  end

  def score_sign4
    score4 >= 0 ? 'pos' : 'neg'
  end

  def scores
    [score1, score2, score3, score4]
  end

  def max_score
    scores.compact.max
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    if (params[:player])
      player_id = Player.select('id').where(email: params[:player]).limit(1)
      @games = Game.where('owner_id = (?)', player_id).order(created_at: :DESC)
    else
      @games = Game.all.order(created_at: :DESC)
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @round = params[:round_id].blank? ? @game.rounds.new : Round.find(params[:round_id])
    @rounds = @game.rounds.order(created_at: :ASC)
    @rounds_count = @game.rounds.count
  end

  # GET /games/new
  def new
    @game = Game.new_from_ip(request.remote_ip)
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    if params[:game]
      @game = Game.create(game_params)
    else
      @game = Game.new_from_ip(request.remote_ip)
    end
    #
    if @game.save
      redirect_to game_path(@game) # with turbolinks
    else
      render layout: false, status: :bad_request
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    if @game.update(game_params)
      redirect_to game_path(@game) # with turbolinks
    else
      render layout: false, status: :bad_request
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    redirect_to games_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:player1, :player2, :player3, :player4, :name)
    end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update, :destroy]

  # GET /rounds
  # GET /rounds.json
  def index
    raise "not supported"
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
    raise "not supported"
  end

  # GET /rounds/new
  def new
    raise "not supported"
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)
    @round.save!
    notify_clients
    head :ok
  rescue
    render layout: false, status: :bad_request
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    @round.update!(round_params)
    notify_clients
    redirect_to game_path(@round.game) # with turbolinks
  rescue
    render layout: false, status: :bad_request
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    game = @round.game
    @round.destroy
    redirect_to edit_game_path(game), notice: 'Round was successfully destroyed.'
  end

  private

    def notify_clients
      rounds = @round.game.rounds.order(created_at: :ASC)
      rounds_count = @round.game.rounds.count
      rounds_html = ApplicationController.render(partial: 'games/rounds', locals: { rounds: rounds, rounds_count: rounds_count })
      ActionCable.server.broadcast("game/#{@round.game.id}", { message: 'scores', scores: @round.game.scores, rounds_html: rounds_html } )
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:game_id, :score1, :score2, :score3, :score4, :roundtype)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/games/_form.slim
.container-fluid
  = form_with model: @game do |f|
    .form-row
      .form-group.col
        label Name
        input.form-control type="text" value=@game.name name="game[name]"
    .form-row
      .form-group.col
        label Player 1
        input.form-control type="text" value=@game.player1 name="game[player1]"
      .form-group.col
        label Player 2
        input.form-control type="text" value=@game.player2 name="game[player2]"
      .form-group.col
        label Player 3
        input.form-control type="text" value=@game.player3 name="game[player3]"
      .form-group.col
        label Player 4
        input.form-control type="text" value=@game.player4 name="game[player4]"

    button.btn.btn-secondary type="submit" value="Save" data-disable-with="..."
      i.fa.fa-save

app/views/games/_rounds.slim
- if rounds_count == 0
  p Enter your first round score
- else
  - rounds.each_with_index.reverse_each do |round, index|
    .form-row
      .col.text-right ##{index+1}
      .col.score.text-center class=round.score_sign1 = round.score1
      .col.score.text-center class=round.score_sign2 = round.score2
      .col.score.text-center class=round.score_sign3 = round.score3
      .col.score.text-center class=round.score_sign4 = round.score4
      .col
        => link_to edit_round_path(round) do
            i.fa.fa-edit

app/views/games/create.js.erb
alert("<%= @game.errors.full_messages.to_sentence %>");

app/views/games/edit.slim
nav aria-label="breadcrumb"
  ol.breadcrumb.bg-transparent
    li.breadcrumb-item
      a.active href=root_path
        i.fa.fa-home
    li.breadcrumb-item.active aria-current="page"
      a href=games_path Games
    li.breadcrumb-item.active aria-current="page"
      a href=game_path(@game) =@game.name

== render 'form'

app/views/games/index.html.slim
.container-fluid
  nav.row aria-label="breadcrumb"
    ol.breadcrumb.bg-transparent
      li.breadcrumb-item
        a.active href=root_path
          i.fa.fa-home
      li.breadcrumb-item.active aria-current="page"
        a href=games_path Games
      li.breadcrumb-item.active aria-current="page"
        = link_to new_game_path do
          i.fa.fa-plus

  - @games.each do |game|
    .game.card.mt-4
      .card-header.text-center
        = link_to game_path(game) do
          => game.name
      .card-body
        .row
          .col.name.text-center class=game.winner1 #{game.player1}
          .col.name.text-center class=game.winner2 #{game.player2}
          .col.name.text-center class=game.winner3 #{game.player3}
          .col.name.text-center class=game.winner4 #{game.player4}
        .row
          .col.score.text-center class=game.score_sign1 #{game.score1}
          .col.score.text-center class=game.score_sign2 #{game.score2}
          .col.score.text-center class=game.score_sign3 #{game.score3}
          .col.score.text-center class=game.score_sign4 #{game.score4}

app/views/games/new.slim
nav aria-label="breadcrumb"
  ol.breadcrumb.bg-transparent
    li.breadcrumb-item
      a.active href=root_path
        i.fa.fa-home
    li.breadcrumb-item.active aria-current="page"
      a href=games_path Games
    li.breadcrumb-item.active aria-current="page" New

== render 'form'

app/views/games/show.html.slim
nav aria-label="breadcrumb"
  ol.breadcrumb.bg-transparent
    li.breadcrumb-item
      a.active href=root_path
        i.fa.fa-home
    li.breadcrumb-item.active aria-current="page"
      a href=games_path Games
    li.breadcrumb-item.active aria-current="page"
      => @game.name
      => link_to edit_game_path(@game) do
        i.fa.fa-edit

.container-fluid data-controller="game" data-game-id=@game.id
  .form-row
    .col.text-center
    .col.name.text-center class=@game.winner1 =@game.player1
    .col.name.text-center class=@game.winner2 =@game.player2
    .col.name.text-center class=@game.winner3 =@game.player3
    .col.name.text-center class=@game.winner4 =@game.player4
    .col

  hr

  .form-row.total
    .col.text-center Score
    .col.score.text-center data-target="game.score1" class=@game.score_sign1 = @game.score1
    .col.score.text-center data-target="game.score2" class=@game.score_sign2 = @game.score2
    .col.score.text-center data-target="game.score3" class=@game.score_sign3 = @game.score3
    .col.score.text-center data-target="game.score4" class=@game.score_sign4 = @game.score4
    .col

  hr

  = form_with model: @round, data: { target: "game.roundForm" } do |f|
    / -if @round.errors.any?
    /   #error_explanation
    /     ul
    /       - @round.errors.full_messages.each do |msg|
    /         li= msg
    input type="hidden" value=@game.id name="round[game_id]"
    .form-row
      .col.text-center
      .col.text-center: input.score.form-control type="number" value=@round.score1 name="round[score1]" onClick="this.select();"
      .col.text-center: input.score.form-control type="number" value=@round.score2 name="round[score2]" onClick="this.select();"
      .col.text-center: input.score.form-control type="number" value=@round.score3 name="round[score3]" onClick="this.select();"
      .col.text-center: input.score.form-control type="number" value=@round.score4 name="round[score4]" onClick="this.select();"
      .col: button.btn.btn-secondary type="submit" value="Save" data-disable-with="..."
        i.fa.fa-save

  hr

  .rounds data-target="game.rounds"
    == render 'rounds', rounds: @rounds, rounds_count: @rounds_count

  hr
  a.btn.btn-danger href=game_path(@game) data-confirm="Are you sure?" data-method="delete"
    i.fa.fa-trash

app/views/games/update.js.erb
alert("<%= @game.errors.full_messages.to_sentence %>");

app/views/layouts/application.html.slim
doctype html
html
  head
    title Whist
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes"
    meta name="mobile-web-app-capable" content="yes"
    meta name="apple-mobile-web-app-capable" content="yes"
    link rel="manifest" href="/manifest.webmanifest"
    link rel="shortcut icon" type="image/png" href="/whist.png"
    link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', async: true
  body
    = yield
    .container-fluid
      p#notice
        dl
          - flash.each do |k, v|
            dd title=k =v
    = javascript_pack_tag 'application', async: true
    = action_cable_meta_tag

app/views/layouts/application.slim
doctype html
html
  head
    title Whist
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application'
    = action_cable_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes"
    meta name="mobile-web-app-capable" content="yes"
    meta name="apple-mobile-web-app-capable" content="yes"

    link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous"
  body
    = yield
    .container-fluid
      p#notice
        dl
          - flash.each do |k, v|
            dd title=k =v

app/views/rounds/create.js.erb
alert("<%= @round.errors.full_messages.to_sentence %>");

app/views/rounds/edit.html.slim
nav aria-label="breadcrumb"
  ol.breadcrumb.bg-transparent
    li.breadcrumb-item
      a.active href=root_path
        i.fa.fa-home
    li.breadcrumb-item.active aria-current="page"
      a href=games_path Games
    li.breadcrumb-item.active aria-current="page"
      => link_to @round.game.name, game_path(@round.game)
    li.breadcrumb-item.active aria-current="page" Edit Round

.form-row
  .col
  .col =@round.game.player1
  .col =@round.game.player2
  .col =@round.game.player3
  .col =@round.game.player4
  .col

= form_with model: @round do |f|
  .form-row
    .col
    .col: input.form-control type="number" value=@round.score1 name="round[score1]" onClick="this.select();"
    .col: input.form-control type="number" value=@round.score2 name="round[score2]" onClick="this.select();"
    .col: input.form-control type="number" value=@round.score3 name="round[score3]" onClick="this.select();"
    .col: input.form-control type="number" value=@round.score4 name="round[score4]" onClick="this.select();"
    .col: button.btn.btn-secondary type="submit" value="Save"
      i.fa.fa-save

app/views/rounds/update.js.erb
alert("<%= @round.errors.full_messages.to_sentence %>");